#!/bin/bash

function atualiza_repositorio(){

echo ""
echo "
deb http://deb.debian.org/debian/ buster main contrib non-free
deb-src http://deb.debian.org/debian/ buster main contrib non-free

deb http://security.debian.org/debian-security buster/updates main contrib non-free
deb-src http://security.debian.org/debian-security buster/updates main contrib non-free

deb http://deb.debian.org/debian/ buster-updates main contrib non-free
deb-src http://deb.debian.org/debian/ buster-updates main contrib non-free " > /etc/apt/sources.list

apt update 
apt upgrade -y

}


function instalar_requisitos(){

apt install -y sudo gdebi-core wget apt-transport-https ca-certificates curl gnupg2 software-properties-common

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

apt update

apt upgrade -y

}


function instalar_docker(){
	
apt install -y docker-ce

}


atualiza_repositorio
instalar_requisitos
instalar_docker


#wget -O - https://raw.githubusercontent.com/lcpcmfafire/scripts/master/instalar_docker | bash
